repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-byte-order-marker
    -   id: check-yaml
        args: ['--unsafe']
    -   id: mixed-line-ending
        args: ['--fix=no']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        args: ['--max-line-length=100']
